name: 📖 Documentation
description: For issues with the documentation
title: Write a short and descriptive title!
labels:
  - docs
body:
  - type: markdown
    attributes:
      value: Thanks for reporting an issue with Scanix documentation. Did you [take a look](https://github.com/shujaakbar2020/scanix/issues?q=is%3Aopen%20is%3Aissue%20label%3Abug) if your issue has already been filed? If so, join the discussion there! Is your issue related to Scanix? Please file it [here](https://github.com/shujaakbar2020/scanix/issues) instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue.
      placeholder: Terse and specific description of the issue. You can add a screenshot by dragging an image here.
    validations:
      required: true
