name: 🪴 Feature Request
description: For feature requests for the Scanix
title: Write a short and descriptive title!
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: Thanks for sharing your feature request for the Scanix. Did you [take a look](https://github.com/shujaakbar2020/scanix/issues?q=is%3Aopen%20is%3Aissue%20label%3Abug) if a similar request has already been filed? If so, join the discussion there! Is your feature request related to Scanix? Please file it [here](https://github.com/shujaakbar2020/scanix/issues) instead.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your feature request. You can also add a mockup if you are requesting a new output feature!
      placeholder: Terse and specific description of the feature. You can add an image by dragging a file here.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Please describe why this feature would be useful.
      placeholder: Describe what users can accomplish with this feature and whom it might be useful for.
    validations:
      required: true
